import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>template</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      
    </>
  );
};

export default Index;
